# H2 内存数据库测试模式 (专为未安装 MySQL 的项目组成员提供)
spring.datasource.url=jdbc:h2:mem:web;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:sys_user.sql

spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER
mybatis.mapper-locations=classpath:mapping/online/*.xml
mybatis.type-aliases-package=com.tongji.enso.mybatisdemo.entity.online
server.port=8888
